resolver: nightly-2017-08-25

flags:
  Taiji-RNA-seq:
    exe: true

packages:
- '.'
- '../SciFlow'
- '../bio-pipelines'
- '../bio-experiments'

extra-deps:
- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- cereal-vector-0.2.0.1
- drmaa-0.2.0
