resolver: lts-11.1

flags:
  Taiji-RNA-seq:
    exe: true

packages:
- '.'
- '../SciFlow'
- '../bio-pipelines'
- '../bio-experiments'
- '../bioinformatics-toolkit/bioinformatics-toolkit'

extra-deps:
- HsHTSLib-1.3.2.3
- cereal-vector-0.2.0.1
- drmaa-0.2.0
- clustering-0.4.0
- graphviz-2999.19.0.0
- fgl-5.5.4.0
