resolver: nightly-2017-08-08

flags:
  Taiji-RNA-seq:
    exe: true

packages:
- '.'
- '../SciFlow'
#- '../bio-pipelines'

- location:
    git: https://github.com/Taiji-pipeline/bio-pipelines.git
    commit: 3968132a8ba36aeaf77562d62d7861c85c61083e

- location:
    git: https://github.com/Taiji-pipeline/bio-experiments.git
    commit: 821fa7d109fb535a7eea389a49c45e51b3b37242

extra-deps:
- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- cereal-vector-0.2.0.1
- rainbow-0.28.0.4
- lens-simple-0.1.0.9
- drmaa-0.2.0
