resolver: nightly-2017-08-25

flags:
  Taiji-RNA-seq:
    exe: true

packages:
- '.'
- '../SciFlow'

- location:
    git: https://github.com/Taiji-pipeline/bio-pipelines.git
    commit: 6f51e476a62b3cedf5e24834311317c84cbd8e8f

- location:
    git: https://github.com/Taiji-pipeline/bio-experiments.git
    commit: bf1d943085c486c0ae3088a21d8375c48323d57a

extra-deps:
- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- cereal-vector-0.2.0.1
- drmaa-0.2.0
