resolver: nightly-2017-08-25

flags:
  Taiji-RNA-seq:
    exe: true

packages:
- '.'
- '../SciFlow'

- location:
    git: https://github.com/Taiji-pipeline/bio-pipelines.git
    commit: 2eda18bc862a27767465126f6a79f7520ae2cf88

- location:
    git: https://github.com/Taiji-pipeline/bio-experiments.git
    commit: 1cd9f244edaacbd1c49b64df127c3943adfcf5d6

extra-deps:
- bioinformatics-toolkit-0.3.2
- HsHTSLib-1.3.2.2
- cereal-vector-0.2.0.1
- drmaa-0.2.0
