resolver: lts-11.5

flags:
  Taiji-RNA-seq:
    exe: true

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  f582814c9151cba26ebe73ef685c68e8de115d6a

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  8d9deaef85b0311d3fe58f3b4cf21efe5e5bf151

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  54aec84485f32b6e822b050c55de9886edefc7c2
  subdirs:
    - bioinformatics-toolkit

- HsHTSLib-1.3.2.3
- drmaa-0.2.0
- clustering-0.4.0
- SciFlow-0.6.2

- graphviz-2999.19.0.0
- fgl-5.5.4.0
