resolver: lts-12.24

flags:
  Taiji-RNA-seq:
    exe: true

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  607bbb44785320d4d0963ed0fc4793f262c0942c

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  19edc88b4bbc7a9ff29ed5bca5d0acf6e2e864b9

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  4d54eab41f76f6fd5a0ffbea9fd52e0b8b6ee829
  subdirs:
    - bioinformatics-toolkit
    
- git:     https://github.com/kaizhang/haskell-igraph.git
  commit:  bdaeae380271fdeb183b1eceafdd0d20b1e38fa3

- HsHTSLib-1.3.2.3
- drmaa-0.2.0
- clustering-0.4.0
- SciFlow-0.6.2