resolver: lts-11.5

flags:
  Taiji-RNA-seq:
    exe: true

packages:
- '.'

extra-deps:

- git:     https://github.com/Taiji-pipeline/bio-pipelines.git
  commit:  067507d696c37a9ccca8a7ae48a7fdd0ae2ec471

- git:     https://github.com/Taiji-pipeline/bio-experiments.git
  commit:  ad9ec54c892ee2942e2314f7982712e18c25ce99

- git:     https://github.com/kaizhang/SciFlow.git
  commit:  a9eed834d5f6db685b95887b715293f6bf2c6b59

- git:     https://github.com/kaizhang/bioinformatics-toolkit.git
  commit:  54aec84485f32b6e822b050c55de9886edefc7c2
  subdirs:
    - bioinformatics-toolkit

- HsHTSLib-1.3.2.3
- drmaa-0.2.0
- clustering-0.4.0

- graphviz-2999.19.0.0
- fgl-5.5.4.0
